<a href="https://colab.research.google.com/github/abulhassanraza/piaic_q2_Assignments/blob/master/Roll_148560_assignment_No_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
x = np.array(range(10,50))

In [4]:
np.shape(x)

(40,)

In [5]:
type(x)

numpy.ndarray

In [6]:
print (np.__version__)
print("__________")
print(np.show_config())

1.18.5
__________
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


In [7]:
x.ndim

1

In [8]:
#boolean array with all true values
a = np.array(range(1,10))
a>0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [9]:
#two dimentional array
h = np.array(range(9)).reshape(3,3)
h

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
#three dimentional array
arr3d = np.array(range(32)).reshape(2,4,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [11]:
#reversing an element in numpy

In [12]:
#Creating a null vector of size 10 but the fifth value which is 1
y = np.zeros(10)
y[4] = 1
y

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [13]:
#Create a 3x3 identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
#Convert the data type of the given array from int to float
arr = np.array([1, 2, 3, 4, 5])
arr.astype('float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [15]:
#Multiply arr1 with arr2
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [16]:
# make an array by comoarison

arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

arr1 == arr2

array([[False, False, False],
       [False, False, False]])

In [17]:
#Extract all odd numbers from arr with values(0-9)

t = np.array(range(1,10))
t [0:10:2]

array([1, 3, 5, 7, 9])

In [18]:
#Replace all odd numbers to -1 from previous array

t = np.array(range(1,10))
t [0:10:2] = -1
t

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

In [19]:
#Replace the values of indexes 5,6,7 and 8 to 12

arr = np.arange(10)

arr [5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [20]:
#Create a 2d array with 1 on the border and 0 inside

bord1 = np.ones((4,4))
bord1 [1:-1,1:-1] =0
bord1

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [21]:
#Replace the value 5 to 12
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

arr2d [1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [22]:
#Convert all the values of 1st array to 64

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d [0] = 64

arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
#Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [29]:
r = np.array(range(0,9)).reshape(3,3)

In [30]:
r [0]

array([0, 1, 2])

In [39]:
#Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

f = np.array(range(0,9)).reshape(3,3)
f

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
#Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

a = np.array(range(0,9)).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
a [::,2]

array([2])

In [50]:
#Create a 10x10 array with random values and find the minimum and maximum values

z = np.random.randn(10,10)

In [54]:
np.amax(z)

2.6788575754196486

In [55]:
np.amin(z)

-2.8620003100289595

In [57]:
#Find the common items between a and b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

In [61]:
#Find the positions where elements of a and b match

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

result = np.where(a == b)
result

(array([1, 3, 5, 7]),)